[package]
name = "entity-query"
version = "0.1.0"
authors = ["Alex Angelini <alex.louis.angelini@gmail.com>"]

[dependencies]
regex = "0.1"
rustc-serialize = "0.3"
bincode = "0.4"
csv = "0.14"
linenoise-rust = "0.1"
flate2 = "0.2"
time = "0.1"
